# Generated by Django 4.1.7 on 2023-03-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_projectdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
