# Generated by Django 4.1.7 on 2023-03-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_remove_projectdetail_description_project_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='ProjectDetail',
            new_name='SensorDetail',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='project',
            new_name='sensor',
        ),
    ]
