# Generated by Django 4.1.7 on 2023-03-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_rename_project_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordetail',
            old_name='name',
            new_name='sensor',
        ),
    ]
