# Generated by Django 4.1.7 on 2023-03-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_rename_name_sensordetail_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordetail',
            old_name='sensor',
            new_name='name',
        ),
    ]
