# Generated by Django 4.1.7 on 2023-03-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0010_alter_sensordetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordetail',
            old_name='name',
            new_name='sensor',
        ),
    ]
