# Generated by Django 4.1.7 on 2023-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0011_rename_name_sensordetail_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sensordetail',
            name='measurements',
            field=models.ManyToManyField(related_name='sensors', to='measurements.measurement'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
