# Generated by Django 4.1.7 on 2023-03-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0012_remove_sensor_latitude_remove_sensor_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordetail',
            name='sensor',
        ),
    ]
