# Generated by Django 4.1.7 on 2023-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0014_delete_sensordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
