# Generated by Django 4.1.7 on 2023-03-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0016_remove_measurement_name_remove_sensor_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.sensor'),
        ),
    ]
